site_name: PyTorch tutorials 中文翻译笔记
repo_name: tanbro/pytorch-tutorials-notebooks-zhs
repo_url: https://github.com/tanbro/pytorch-tutorials-notebooks-zhs

plugins:
    - search
    - pdf-export:
        enabled_if_env: MKDOCS_PDF_EXPORT
        combined: True

theme:
    name: material
    font: False
    language: zh

extra:
    manifest: manifest.webmanifest

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: False
        linenums: True
    - def_list
    - meta
    - sane_lists
    - toc:
        permalink: True
        baselevel: 2
        slugify: slugify.slugify
    - pymdownx.extra
    - pymdownx.arithmatex

nav:
    - README: README.md
    - 入门:
        - 60分钟闪电战:
            - 什么是PyTorch？: beginner/blitz/tensor_tutorial.md
            - Autograd：自动微分: beginner/blitz/autograd_tutorial.md
            - 神经网络: beginner/blitz/neural_networks_tutorial.md
            - 训练分类器: beginner/blitz/cifar10_tutorial.md
            - 数据并行: beginner/blitz/data_parallel_tutorial.md
        - 数据加载和处理教程: beginner/data_loading_tutorial.md
        - 迁移学习教程: beginner/transfer_learning_tutorial.md
    - 文本:
        - 聊天机器人教程: beginner/chatbot_tutorial.md
